# Generated by Django 5.0.2 on 2024-02-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('todo', 'todo'), ('in progress', 'in progress'), ('completed', 'completed')], default='todo', max_length=255)),
            ],
        ),
    ]
